name: Build and Release VSCode Extension

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Ensure this matches your project's requirements

      # Step 3: Install dependencies and build package
      - name: Install dependencies
        run: npm install

      - name: Build the VSCode extension package
        run: vcse package

      # Step 4: Determine the release tag
      - name: Extract release tag
        id: extract_tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "release_tag=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "release_tag=latest" >> $GITHUB_ENV
          fi
        shell: bash

      # Step 5: Create a GitHub release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        if: ${{ github.ref_type == 'tag' || github.ref_name == 'master' }}
        with:
          tag_name: ${{ env.release_tag }}
          release_name: ${{ env.release_tag }}
          body: "Release generated by GitHub Actions for ${{ env.release_tag }}"
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Upload the VSIX file to the release
      - name: Upload VSIX to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.extract_tag.outputs.release_url }}
          asset_path: './*.vsix'
          asset_name: '${{ env.release_tag }}.vsix'
          asset_content_type: application/octet-stream
